#!/bin/sh

# Script for installation of PRISM on a clean install of Cygwin
# already set up with required packages, e.g., via prism-install-windows.bat

set -e # Abort if one of the commands fails
set -x # Print commands as they are executed

# Download the latest development version from GitHub
git clone https://github.com/prismmodelchecker/prism.git

# Compile PRISM and run a single test (unless --nobuild passed)
# (should ultimately display: "Testing result: PASS")
if [ "$*" = "${*/--nobuild}" ]; then
  (cd prism/prism && make && make test)
fi
