#!/bin/sh

# Script for installation of PRISM on a clean install of Ubuntu

set -e # Abort if one of the commands fail
set -x # Print commands as they are executed

# Install dependencies: make/gcc/Java
sudo apt-get update
sudo apt -y install make gcc g++ default-jdk git

# Install Python (only needed for testing (prism-auto) currently)
sudo apt -y install python

# Download the latest development version from GitHub
git clone https://github.com/prismmodelchecker/prism.git

# Compile PRISM and run a single test
# (should ultimately display: "Testing result: PASS")
(cd prism/prism && make && make test)
