#!/bin/csh

prism dining_crypt3.nm  correctness3.pctl
prism dining_crypt4.nm  correctness4.pctl
prism dining_crypt5.nm  correctness5.pctl
prism dining_crypt6.nm  correctness6.pctl
prism dining_crypt7.nm  correctness7.pctl
prism dining_crypt8.nm  correctness8.pctl
prism dining_crypt9.nm  correctness9.pctl
prism dining_crypt10.nm correctness10.pctl
prism dining_crypt15.nm correctness15.pctl

prism dining_crypt3.nm  anonymity3.pctl  -const k=0 -m -nopre
prism dining_crypt4.nm  anonymity4.pctl  -const k=1 -m -nopre
prism dining_crypt5.nm  anonymity5.pctl  -const k=0 -m -nopre
prism dining_crypt6.nm  anonymity6.pctl  -const k=1 -m -nopre
prism dining_crypt7.nm  anonymity7.pctl  -const k=0 -m -nopre
prism dining_crypt8.nm  anonymity8.pctl  -const k=1 -m -nopre
prism dining_crypt9.nm  anonymity9.pctl  -const k=0 -m -nopre
prism dining_crypt10.nm anonymity10.pctl -const k=1 -m -nopre
prism dining_crypt15.nm anonymity15.pctl -const k=0 -m -nopre
