#!/bin/csh

prism csma2_2.nm csma.pctl -s
prism csma2_4.nm csma.pctl -s
prism csma2_6.nm csma.pctl -s
prism csma3_2.nm csma.pctl -s
prism csma3_4.nm csma.pctl -s
prism csma3_6.nm csma.pctl -s
prism csma4_2.nm csma.pctl -s
#prism csma4_4.nm csma.pctl -s
#prism csma4_6.nm csma.pctl -s

