#!/bin/csh

prism csma2_2.nm csma2.pctl
prism csma2_3.nm csma2.pctl
prism csma2_4.nm csma2.pctl
prism csma4_2.nm csma4.pctl
prism csma4_3.nm csma4.pctl
prism csma4_4.nm csma4.pctl
prism csma6_2.nm csma6.pctl
prism csma6_3.nm csma6.pctl
prism csma6_4.nm csma6.pctl

