# Travis CI configuration

# xenial (has build-essential) + Java
dist: xenial
# we are requiring VM instead of Docker builds due to sporadic nailgun test suite failures
sudo: required
language: java

# we test for JDK 10,11
jdk:
  - openjdk10
  - openjdk11
  
# compile and run the test suite
# we manually set PRISM_JAVA to the java on the PATH as the python invocation of prism-auto fiddles with the PATH variable...  
script: >
  cd prism &&
  make &&
  echo 'Compilation successful, running test suite....' && echo &&
  export PRISM_JAVA=`which java` &&
  make tests &&
  echo && echo 'Yay'


# notifications
notifications:
  email:
    recipients:
      - d.a.parker@cs.bham.ac.uk
      - klein@tcs.inf.tu-dresden.de
    on_success: change
    on_failure: always
