#!/bin/csh

prism csma.nm eventually.pctl -aroptions refine=all,nopre,opt -const bmax=1

prism csma.nm deadline.pctl -const bmax=1 -const T=1000 -aroptions refine=all,nopre,opt
prism csma.nm deadline.pctl -const bmax=1 -const T=2000 -aroptions refine=all,nopre,opt
prism csma.nm deadline.pctl -const bmax=1 -const T=3000 -aroptions refine=all,nopre,opt
