#!/bin/csh

prism csma.nm collisions.pctl -const bmax=2,K=4 -aroptions refine=all,nopre,opt
prism csma.nm collisions.pctl -const bmax=2,K=8 -aroptions refine=all,nopre,opt
prism csma.nm collisions.pctl -const bmax=4,K=4 -aroptions refine=all,nopre,opt
prism csma.nm collisions.pctl -const bmax=4,K=8 -aroptions refine=all,nopre,opt

prism csma.nm time.pctl -const bmax=1,K=0 -aroptions refine=all,nopre,opt
prism csma.nm time.pctl -const bmax=2,K=0 -aroptions refine=all,nopre,opt
prism csma.nm time.pctl -const bmax=3,K=0 -aroptions refine=all,nopre,opt
prism csma.nm time.pctl -const bmax=4,K=0 -aroptions refine=all,nopre,opt