/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jdd_DebugJDD */

#ifndef _Included_jdd_DebugJDD
#define _Included_jdd_DebugJDD
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jdd_DebugJDD
 * Method:    DebugJDD_GetRefCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jdd_DebugJDD_DebugJDD_1GetRefCount
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jdd_DebugJDD
 * Method:    DebugJDD_GetExternalRefCounts
 * Signature: ()[J
 */
JNIEXPORT jlongArray JNICALL Java_jdd_DebugJDD_DebugJDD_1GetExternalRefCounts
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class jdd_DebugJDD_DebugJDDNodeLight */

#ifndef _Included_jdd_DebugJDD_DebugJDDNodeLight
#define _Included_jdd_DebugJDD_DebugJDDNodeLight
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class jdd_DebugJDD_DebugJDDNode */

#ifndef _Included_jdd_DebugJDD_DebugJDDNode
#define _Included_jdd_DebugJDD_DebugJDDNode
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
