/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dv_IntegerVector */

#ifndef _Included_dv_IntegerVector
#define _Included_dv_IntegerVector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dv_IntegerVector
 * Method:    IV_CreateZeroVector
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_dv_IntegerVector_IV_1CreateZeroVector
  (JNIEnv *, jobject, jint);

/*
 * Class:     dv_IntegerVector
 * Method:    IV_ConvertMTBDD
 * Signature: (JJIJ)J
 */
JNIEXPORT jlong JNICALL Java_dv_IntegerVector_IV_1ConvertMTBDD
  (JNIEnv *, jobject, jlong, jlong, jint, jlong);

/*
 * Class:     dv_IntegerVector
 * Method:    IV_GetElement
 * Signature: (JII)I
 */
JNIEXPORT jint JNICALL Java_dv_IntegerVector_IV_1GetElement
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     dv_IntegerVector
 * Method:    IV_SetElement
 * Signature: (JIII)V
 */
JNIEXPORT void JNICALL Java_dv_IntegerVector_IV_1SetElement
  (JNIEnv *, jobject, jlong, jint, jint, jint);

/*
 * Class:     dv_IntegerVector
 * Method:    IV_SetAllElements
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_dv_IntegerVector_IV_1SetAllElements
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     dv_IntegerVector
 * Method:    IV_Clear
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_dv_IntegerVector_IV_1Clear
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
