/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jdd_JDDNode */

#ifndef _Included_jdd_JDDNode
#define _Included_jdd_JDDNode
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jdd_JDDNode
 * Method:    DDN_IsConstant
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_jdd_JDDNode_DDN_1IsConstant
  (JNIEnv *, jobject, jlong);

/*
 * Class:     jdd_JDDNode
 * Method:    DDN_GetIndex
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jdd_JDDNode_DDN_1GetIndex
  (JNIEnv *, jobject, jlong);

/*
 * Class:     jdd_JDDNode
 * Method:    DDN_GetValue
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_jdd_JDDNode_DDN_1GetValue
  (JNIEnv *, jobject, jlong);

/*
 * Class:     jdd_JDDNode
 * Method:    DDN_GetThen
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jdd_JDDNode_DDN_1GetThen
  (JNIEnv *, jobject, jlong);

/*
 * Class:     jdd_JDDNode
 * Method:    DDN_GetElse
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jdd_JDDNode_DDN_1GetElse
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
