/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class odd_ODDUtils */

#ifndef _Included_odd_ODDUtils
#define _Included_odd_ODDUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     odd_ODDUtils
 * Method:    ODD_SetCUDDManager
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_odd_ODDUtils_ODD_1SetCUDDManager
  (JNIEnv *, jclass, jint);

/*
 * Class:     odd_ODDUtils
 * Method:    ODD_BuildODD
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_odd_ODDUtils_ODD_1BuildODD
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     odd_ODDUtils
 * Method:    ODD_GetNumODDNodes
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_odd_ODDUtils_ODD_1GetNumODDNodes
  (JNIEnv *, jclass);

/*
 * Class:     odd_ODDUtils
 * Method:    ODD_GetTOff
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_odd_ODDUtils_ODD_1GetTOff
  (JNIEnv *, jclass, jint);

/*
 * Class:     odd_ODDUtils
 * Method:    ODD_GetEOff
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_odd_ODDUtils_ODD_1GetEOff
  (JNIEnv *, jclass, jint);

/*
 * Class:     odd_ODDUtils
 * Method:    ODD_GetThen
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_odd_ODDUtils_ODD_1GetThen
  (JNIEnv *, jclass, jint);

/*
 * Class:     odd_ODDUtils
 * Method:    ODD_GetElse
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_odd_ODDUtils_ODD_1GetElse
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
