/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class prism_PrismNative */

#ifndef _Included_prism_PrismNative
#define _Included_prism_PrismNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     prism_PrismNative
 * Method:    PN_SetExportAdv
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_prism_PrismNative_PN_1SetExportAdv
  (JNIEnv *, jclass, jint);

/*
 * Class:     prism_PrismNative
 * Method:    PN_SetExportAdvFilename
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_prism_PrismNative_PN_1SetExportAdvFilename
  (JNIEnv *, jclass, jstring);

/*
 * Class:     prism_PrismNative
 * Method:    PN_GetStdout
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_prism_PrismNative_PN_1GetStdout
  (JNIEnv *, jclass);

/*
 * Class:     prism_PrismNative
 * Method:    PN_OpenFile
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_prism_PrismNative_PN_1OpenFile
  (JNIEnv *, jclass, jstring);

/*
 * Class:     prism_PrismNative
 * Method:    PN_OpenFileAppend
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_prism_PrismNative_PN_1OpenFileAppend
  (JNIEnv *, jclass, jstring);

/*
 * Class:     prism_PrismNative
 * Method:    PN_PrintToFile
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_prism_PrismNative_PN_1PrintToFile
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     prism_PrismNative
 * Method:    PN_FlushFile
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_prism_PrismNative_PN_1FlushFile
  (JNIEnv *, jclass, jlong);

/*
 * Class:     prism_PrismNative
 * Method:    PN_CloseFile
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_prism_PrismNative_PN_1CloseFile
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
