/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class prism_PrismUtils */

#ifndef _Included_prism_PrismUtils
#define _Included_prism_PrismUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     prism_PrismUtils
 * Method:    PU_GetStdout
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_prism_PrismUtils_PU_1GetStdout
  (JNIEnv *, jclass);

/*
 * Class:     prism_PrismUtils
 * Method:    PU_OpenFile
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_prism_PrismUtils_PU_1OpenFile
  (JNIEnv *, jclass, jstring);

/*
 * Class:     prism_PrismUtils
 * Method:    PU_PrintToFile
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_prism_PrismUtils_PU_1PrintToFile
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     prism_PrismUtils
 * Method:    PU_FlushFile
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_prism_PrismUtils_PU_1FlushFile
  (JNIEnv *, jclass, jlong);

/*
 * Class:     prism_PrismUtils
 * Method:    PU_CloseFile
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_prism_PrismUtils_PU_1CloseFile
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
