#!/bin/csh

prism herman3.pm herman3.pctl -prop 1 -const k=0
prism herman3.pm herman3.pctl -prop 2 -const k=1:1:100
prism herman3.pm herman3.pctl -prop 3 -const k=0
prism herman3.pm herman3.pctl -prop 4 -const k=1:2:3
prism herman3.pm herman3.pctl -prop 5 -const k=1:2:3
