#!/bin/csh

prism herman7.pm herman7.pctl -prop 1 -const k=0
prism herman7.pm herman7.pctl -prop 2 -const k=0
prism herman7.pm herman7.pctl -prop 3 -const k=1:2:7
prism herman7.pm herman7.pctl -prop 4 -const k=1:2:7
