/* Generated By:JavaCC: Do not edit this line. Prism3To4Constants.java */
package parser;

public interface Prism3To4Constants {

  int EOF = 0;
  int WHITESPACE = 1;
  int COMMENT = 2;
  int BOOL = 3;
  int CONST = 4;
  int CEIL = 5;
  int CTMC = 6;
  int CUMUL = 7;
  int DOUBLE = 8;
  int DTMC = 9;
  int ENDINIT = 10;
  int ENDMODULE = 11;
  int ENDREWARDS = 12;
  int ENDSYSTEM = 13;
  int FALSE = 14;
  int FLOOR = 15;
  int FORMULA = 16;
  int FUNC = 17;
  int FUTURE = 18;
  int GLOBAL = 19;
  int GLOB = 20;
  int INIT = 21;
  int INST = 22;
  int INT = 23;
  int LABEL = 24;
  int MAX = 25;
  int MDP = 26;
  int MIN = 27;
  int MODULE = 28;
  int NEXT = 29;
  int NONDETERMINISTIC = 30;
  int PMAX = 31;
  int PMIN = 32;
  int P = 33;
  int PROBABILISTIC = 34;
  int PROB = 35;
  int RATE = 36;
  int REWARDS = 37;
  int RMAX = 38;
  int RMIN = 39;
  int R = 40;
  int S = 41;
  int STOCHASTIC = 42;
  int SYSTEM = 43;
  int TRUE = 44;
  int UNTIL = 45;
  int NOT = 46;
  int AND = 47;
  int OR = 48;
  int IMPLIES = 49;
  int RARROW = 50;
  int COLON = 51;
  int SEMICOLON = 52;
  int COMMA = 53;
  int DOTS = 54;
  int LPARENTH = 55;
  int RPARENTH = 56;
  int LBRACKET = 57;
  int RBRACKET = 58;
  int LBRACE = 59;
  int RBRACE = 60;
  int EQ = 61;
  int NE = 62;
  int LT = 63;
  int GT = 64;
  int LE = 65;
  int GE = 66;
  int PLUS = 67;
  int MINUS = 68;
  int TIMES = 69;
  int DIVIDE = 70;
  int PRIME = 71;
  int RENAME = 72;
  int QMARK = 73;
  int DQUOTE = 74;
  int REG_INT = 75;
  int REG_DOUBLE = 76;
  int REG_IDENTPRIME = 77;
  int REG_IDENT = 78;
  int PREPROC = 79;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "<WHITESPACE>",
    "<COMMENT>",
    "\"bool\"",
    "\"const\"",
    "\"ceil\"",
    "\"ctmc\"",
    "\"C\"",
    "\"double\"",
    "\"dtmc\"",
    "\"endinit\"",
    "\"endmodule\"",
    "\"endrewards\"",
    "\"endsystem\"",
    "\"false\"",
    "\"floor\"",
    "\"formula\"",
    "\"func\"",
    "\"F\"",
    "\"global\"",
    "\"G\"",
    "\"init\"",
    "\"I\"",
    "\"int\"",
    "\"label\"",
    "\"max\"",
    "\"mdp\"",
    "\"min\"",
    "\"module\"",
    "\"X\"",
    "\"nondeterministic\"",
    "\"Pmax\"",
    "\"Pmin\"",
    "\"P\"",
    "\"probabilistic\"",
    "\"prob\"",
    "\"rate\"",
    "\"rewards\"",
    "\"Rmax\"",
    "\"Rmin\"",
    "\"R\"",
    "\"S\"",
    "\"stochastic\"",
    "\"system\"",
    "\"true\"",
    "\"U\"",
    "\"!\"",
    "\"&\"",
    "\"|\"",
    "\"=>\"",
    "\"->\"",
    "\":\"",
    "\";\"",
    "\",\"",
    "\"..\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\"=\"",
    "\"!=\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"\\\'\"",
    "\"<-\"",
    "\"?\"",
    "\"\\\"\"",
    "<REG_INT>",
    "<REG_DOUBLE>",
    "<REG_IDENTPRIME>",
    "<REG_IDENT>",
    "<PREPROC>",
  };

}
