/* Generated By:JavaCC: Do not edit this line. PrismParserConstants.java */
package parser;

public interface PrismParserConstants {

  int EOF = 0;
  int WHITESPACE = 1;
  int COMMENT = 2;
  int BOOL = 3;
  int CONST = 4;
  int CTMC = 5;
  int C = 6;
  int DOUBLE = 7;
  int DTMC = 8;
  int ENDINIT = 9;
  int ENDMODULE = 10;
  int ENDREWARDS = 11;
  int ENDSYSTEM = 12;
  int FALSE = 13;
  int FORMULA = 14;
  int FUNC = 15;
  int F = 16;
  int GLOBAL = 17;
  int G = 18;
  int INIT = 19;
  int I = 20;
  int INT = 21;
  int LABEL = 22;
  int MAX = 23;
  int MDP = 24;
  int MIN = 25;
  int MODULE = 26;
  int X = 27;
  int NONDETERMINISTIC = 28;
  int PMAX = 29;
  int PMIN = 30;
  int P = 31;
  int PROBABILISTIC = 32;
  int PROB = 33;
  int RATE = 34;
  int REWARDS = 35;
  int RMAX = 36;
  int RMIN = 37;
  int R = 38;
  int S = 39;
  int STOCHASTIC = 40;
  int SYSTEM = 41;
  int TRUE = 42;
  int U = 43;
  int W = 44;
  int NOT = 45;
  int AND = 46;
  int OR = 47;
  int IMPLIES = 48;
  int RARROW = 49;
  int COLON = 50;
  int SEMICOLON = 51;
  int COMMA = 52;
  int DOTS = 53;
  int LPARENTH = 54;
  int RPARENTH = 55;
  int LBRACKET = 56;
  int RBRACKET = 57;
  int LBRACE = 58;
  int RBRACE = 59;
  int EQ = 60;
  int NE = 61;
  int LT = 62;
  int GT = 63;
  int LE = 64;
  int GE = 65;
  int PLUS = 66;
  int MINUS = 67;
  int TIMES = 68;
  int DIVIDE = 69;
  int PRIME = 70;
  int RENAME = 71;
  int QMARK = 72;
  int DQUOTE = 73;
  int REG_INT = 74;
  int REG_DOUBLE = 75;
  int REG_IDENTPRIME = 76;
  int REG_IDENT = 77;
  int PREPROC = 78;
  int LEXICAL_ERROR = 79;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "<WHITESPACE>",
    "<COMMENT>",
    "\"bool\"",
    "\"const\"",
    "\"ctmc\"",
    "\"C\"",
    "\"double\"",
    "\"dtmc\"",
    "\"endinit\"",
    "\"endmodule\"",
    "\"endrewards\"",
    "\"endsystem\"",
    "\"false\"",
    "\"formula\"",
    "\"func\"",
    "\"F\"",
    "\"global\"",
    "\"G\"",
    "\"init\"",
    "\"I\"",
    "\"int\"",
    "\"label\"",
    "\"max\"",
    "\"mdp\"",
    "\"min\"",
    "\"module\"",
    "\"X\"",
    "\"nondeterministic\"",
    "\"Pmax\"",
    "\"Pmin\"",
    "\"P\"",
    "\"probabilistic\"",
    "\"prob\"",
    "\"rate\"",
    "\"rewards\"",
    "\"Rmax\"",
    "\"Rmin\"",
    "\"R\"",
    "\"S\"",
    "\"stochastic\"",
    "\"system\"",
    "\"true\"",
    "\"U\"",
    "\"W\"",
    "\"!\"",
    "\"&\"",
    "\"|\"",
    "\"=>\"",
    "\"->\"",
    "\":\"",
    "\";\"",
    "\",\"",
    "\"..\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\"=\"",
    "\"!=\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"\\\'\"",
    "\"<-\"",
    "\"?\"",
    "\"\\\"\"",
    "<REG_INT>",
    "<REG_DOUBLE>",
    "<REG_IDENTPRIME>",
    "<REG_IDENT>",
    "<PREPROC>",
    "<LEXICAL_ERROR>",
  };

}
