#!/bin/csh

# liveness
prism firewire.nm liveness.pctl -const delay=36,fast=0.5 -m

# maximum expected time
prism firewire.nm expected.pctl -const delay=3,fast=0.2:0.1:0.8 -prop 1 -s
#prism firewire.nm expected.pctl -const delay=36,fast=0.2:0.1:0.8 -prop 1 =m

# maximum expected time sending
prism firewire.nm expected.pctl -const delay=3,fast=0.2:0.1:0.8 -prop 2 -s
#prism firewire.nm expected.pctl -const delay=36,fast=0.2:0.1:0.8 -prop 2 -m

# deadline properties
foreach deadline (200 300 400) # 500 600 800 1000)
	prism deadline.nm deadline.pctl -const deadline=$deadline,delay=3,fast=0.5 -s
#	prism deadline.nm deadline.pctl -const deadline=$deadline,delay=36,fast=0.5 -m
end

