#! /bin/bash

# Interface wrapper for calling Rabinizer3 (transition-based DGRA)
# Invoke from PRISM with
#  -ltl2datool hoa-rabinizer3-tdgra-for-prism -ltl2dasyntax rabinizer
#
# Expects the rabinizer.jar file of Rabinizer3 in the current directory, otherwise
# specify its location using
#  export RABINIZER3=path/to/rabinizer.jar

# Take location of the jar file from RABINIZER3 environment variable
# Otherwise, default to current directory
RABINIZER3_JAR=${RABINIZER3-./rabinizer.jar}

# -hoa = output HOA
# -gen-edges = output transition-based generalized Rabin
java -jar $RABINIZER3_JAR -hoa -gen-edges "$1"   &&  mv "$1.hoa" "$2"
