#! /bin/bash

# Interface wrapper for calling Spot's ltl2tgba
# Invoke from PRISM with
#  -ltl2datool hoa-ltl2tgba-for-prism -ltl2dasyntax lbt

# Expects the ltl2tgba executable to be on the PATH, otherwise specify its location using
#  export LTL2TGBA=path/to/ltl2tgba

# Take the ltl2tgba executable from the LTL2TGBA environment variable
# Otherwise, default to "ltl2tgba", which will search the PATH
LTL2TGBA_BIN=${LTL2TGBA-ltl2tgba}

# --output=automaton = we want the automaton
# --output-format=hoa = ... in HOA
$LTL2TGBA_BIN --file="$1" --lbt-input --hoaf --output="$2" --generic --deterministic --complete
