# A makefile for the PEPA to PRISM compiler

# Edit this line to locate your copy of the MLj compiler.
#MLJ=/home/mlj/version-0.1/bin/mlj
MLJ=/home/stg/pub/MLj/version-0.1/bin/mlj

# The MLj compiler is available for download from 
# http://www.dcs.ed.ac.uk/home/mlj
# if it is not installed on your system.

# You should not need to edit anything below this line.
all:
	${MLJ} pepa
