#!/bin/csh

prism repudiation.nm eventually.pctl -aroptions refine=all,opt

prism repudiation.nm deadline.pctl -aroptions refine=all,opt -const T=40
prism repudiation.nm deadline.pctl -aroptions refine=all,opt -const T=80
prism repudiation.nm deadline.pctl -aroptions refine=all,opt -const T=100
