#!/bin/csh

prism ij3.nm ij3.pctl -prop 1 -const k=0
prism ij3.nm ij3.pctl -prop 2 -const k=1:1:100 -m
prism ij3.nm ij3.pctl -prop 3 -const k=0 -m
prism ij3.nm ij3.pctl -prop 4 -const k=1:1:3 -m
prism ij3.nm ij3.pctl -prop 5 -const k=1:1:3 -m
