/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dv_DoubleVector */

#ifndef _Included_dv_DoubleVector
#define _Included_dv_DoubleVector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dv_DoubleVector
 * Method:    DV_SetCUDDManager
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_dv_DoubleVector_DV_1SetCUDDManager
  (JNIEnv *, jclass, jint);

/*
 * Class:     dv_DoubleVector
 * Method:    DV_CreateZeroVector
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_dv_DoubleVector_DV_1CreateZeroVector
  (JNIEnv *, jobject, jint);

/*
 * Class:     dv_DoubleVector
 * Method:    DV_ConvertMTBDD
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_dv_DoubleVector_DV_1ConvertMTBDD
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     dv_DoubleVector
 * Method:    DV_GetElement
 * Signature: (III)D
 */
JNIEXPORT jdouble JNICALL Java_dv_DoubleVector_DV_1GetElement
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     dv_DoubleVector
 * Method:    DV_RoundOff
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_dv_DoubleVector_DV_1RoundOff
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     dv_DoubleVector
 * Method:    DV_SubtractFromOne
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_dv_DoubleVector_DV_1SubtractFromOne
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     dv_DoubleVector
 * Method:    DV_Add
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_dv_DoubleVector_DV_1Add
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     dv_DoubleVector
 * Method:    DV_TimesConstant
 * Signature: (IID)V
 */
JNIEXPORT void JNICALL Java_dv_DoubleVector_DV_1TimesConstant
  (JNIEnv *, jobject, jint, jint, jdouble);

/*
 * Class:     dv_DoubleVector
 * Method:    DV_Filter
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_dv_DoubleVector_DV_1Filter
  (JNIEnv *, jobject, jint, jint, jint, jint, jint);

/*
 * Class:     dv_DoubleVector
 * Method:    DV_Clear
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_dv_DoubleVector_DV_1Clear
  (JNIEnv *, jobject, jint);

/*
 * Class:     dv_DoubleVector
 * Method:    DV_GetNNZ
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_dv_DoubleVector_DV_1GetNNZ
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     dv_DoubleVector
 * Method:    DV_FirstFromBDD
 * Signature: (IIIII)D
 */
JNIEXPORT jdouble JNICALL Java_dv_DoubleVector_DV_1FirstFromBDD
  (JNIEnv *, jobject, jint, jint, jint, jint, jint);

/*
 * Class:     dv_DoubleVector
 * Method:    DV_MinOverBDD
 * Signature: (IIIII)D
 */
JNIEXPORT jdouble JNICALL Java_dv_DoubleVector_DV_1MinOverBDD
  (JNIEnv *, jobject, jint, jint, jint, jint, jint);

/*
 * Class:     dv_DoubleVector
 * Method:    DV_MaxOverBDD
 * Signature: (IIIII)D
 */
JNIEXPORT jdouble JNICALL Java_dv_DoubleVector_DV_1MaxOverBDD
  (JNIEnv *, jobject, jint, jint, jint, jint, jint);

/*
 * Class:     dv_DoubleVector
 * Method:    DV_SumOverBDD
 * Signature: (IIIII)D
 */
JNIEXPORT jdouble JNICALL Java_dv_DoubleVector_DV_1SumOverBDD
  (JNIEnv *, jobject, jint, jint, jint, jint, jint);

/*
 * Class:     dv_DoubleVector
 * Method:    DV_SumOverMTBDD
 * Signature: (IIIII)D
 */
JNIEXPORT jdouble JNICALL Java_dv_DoubleVector_DV_1SumOverMTBDD
  (JNIEnv *, jobject, jint, jint, jint, jint, jint);

/*
 * Class:     dv_DoubleVector
 * Method:    DV_BDDGreaterThanEquals
 * Signature: (IDIII)I
 */
JNIEXPORT jint JNICALL Java_dv_DoubleVector_DV_1BDDGreaterThanEquals
  (JNIEnv *, jobject, jint, jdouble, jint, jint, jint);

/*
 * Class:     dv_DoubleVector
 * Method:    DV_BDDGreaterThan
 * Signature: (IDIII)I
 */
JNIEXPORT jint JNICALL Java_dv_DoubleVector_DV_1BDDGreaterThan
  (JNIEnv *, jobject, jint, jdouble, jint, jint, jint);

/*
 * Class:     dv_DoubleVector
 * Method:    DV_BDDLessThanEquals
 * Signature: (IDIII)I
 */
JNIEXPORT jint JNICALL Java_dv_DoubleVector_DV_1BDDLessThanEquals
  (JNIEnv *, jobject, jint, jdouble, jint, jint, jint);

/*
 * Class:     dv_DoubleVector
 * Method:    DV_BDDLessThan
 * Signature: (IDIII)I
 */
JNIEXPORT jint JNICALL Java_dv_DoubleVector_DV_1BDDLessThan
  (JNIEnv *, jobject, jint, jdouble, jint, jint, jint);

/*
 * Class:     dv_DoubleVector
 * Method:    DV_BDDInterval
 * Signature: (IDDIII)I
 */
JNIEXPORT jint JNICALL Java_dv_DoubleVector_DV_1BDDInterval
  (JNIEnv *, jobject, jint, jdouble, jdouble, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
