/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jdd_JDDVars */

#ifndef _Included_jdd_JDDVars
#define _Included_jdd_JDDVars
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jdd_JDDVars
 * Method:    DDV_BuildArray
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jdd_JDDVars_DDV_1BuildArray
  (JNIEnv *, jobject);

/*
 * Class:     jdd_JDDVars
 * Method:    DDV_FreeArray
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jdd_JDDVars_DDV_1FreeArray
  (JNIEnv *, jobject, jint);

/*
 * Class:     jdd_JDDVars
 * Method:    DDV_GetIndex
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_jdd_JDDVars_DDV_1GetIndex
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
