#!/bin/csh

prism beauquier3.nm beauquier.pctl -prop 1 -const k=0,K=0
prism beauquier3.nm beauquier.pctl -prop 2 -const k=0,K=0 -m
prism beauquier3.nm beauquier.pctl -prop 3 -const k=1:2:3,K=0 -m
prism beauquier3.nm beauquier.pctl -prop 4 -const k=1:2:3,K=0 -m
prism beauquier3.nm beauquier.pctl -prop 5 -const k=3,K=1:1:100 -m
